package Graph2D;

import java.awt.*;
import java.awt.geom.Rectangle2D;
import javax.swing.*;
import java.util.*;

public class Graph2D extends JPanel{
    private final int WIDTH = 800, HEIGHT = WIDTH * 9 / 16;
    public float BAR_WIDTH = (float)WIDTH / 25; // bar width
    public int traversing_index = 0;
    public int current_index = 0;
    public int height = 0;
    // last 3 variables not working yet, they will be initialized to values generated by sorting methods when completed

    // repaint() will automatically call this function
    // needed for coloring
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);

        // Drawing the rectangles
        Graphics2D g2d = (Graphics2D)g;
        g2d.setColor(Color.BLACK);
        Rectangle2D.Float bar;

        for(int i = 0; i < 25; i++ ) {
            bar = new Rectangle2D.Float(i * BAR_WIDTH, 0, BAR_WIDTH-1, height);
            g2d.fill(bar); // g2d.draw(bar);
        }

        //code below is unfinished
        // Color setter for the current object
        g2d.setColor(Color.GREEN);
        bar = new Rectangle2D.Float(current_index * BAR_WIDTH, 0, BAR_WIDTH, height);
        g2d.fill(bar);
    }
}